config/routes.rb
Examen::Application.routes.draw do
  resources :calificaciones

end

app/models/calificacione.rb
class Calificacione < ActiveRecord::Base
  attr_accessible :Asignatura, :Catedratico, :Nota, :Observaciones
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/calificaciones_controller.rb
class CalificacionesController < ApplicationController
  # GET /calificaciones
  # GET /calificaciones.json
  def index
    @calificaciones = Calificacione.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @calificaciones }
    end
  end

  # GET /calificaciones/1
  # GET /calificaciones/1.json
  def show
    @calificacione = Calificacione.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @calificacione }
    end
  end

  # GET /calificaciones/new
  # GET /calificaciones/new.json
  def new
    @calificacione = Calificacione.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @calificacione }
    end
  end

  # GET /calificaciones/1/edit
  def edit
    @calificacione = Calificacione.find(params[:id])
  end

  # POST /calificaciones
  # POST /calificaciones.json
  def create
    @calificacione = Calificacione.new(params[:calificacione])

    respond_to do |format|
      if @calificacione.save
        format.html { redirect_to @calificacione, notice: 'Calificacione was successfully created.' }
        format.json { render json: @calificacione, status: :created, location: @calificacione }
      else
        format.html { render action: "new" }
        format.json { render json: @calificacione.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /calificaciones/1
  # PUT /calificaciones/1.json
  def update
    @calificacione = Calificacione.find(params[:id])

    respond_to do |format|
      if @calificacione.update_attributes(params[:calificacione])
        format.html { redirect_to @calificacione, notice: 'Calificacione was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @calificacione.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calificaciones/1
  # DELETE /calificaciones/1.json
  def destroy
    @calificacione = Calificacione.find(params[:id])
    @calificacione.destroy

    respond_to do |format|
      format.html { redirect_to calificaciones_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calificaciones_helper.rb
module CalificacionesHelper
end

app/views/calificaciones/_form.html.erb
<%= form_for(@calificacione) do |f| %>
  <% if @calificacione.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@calificacione.errors.count, "error") %> prohibited this calificacione from being saved:</h2>

      <ul>
      <% @calificacione.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Asignatura %><br />
    <%= f.text_area :Asignatura %>
  </div>
  <div class="field">
    <%= f.label :Catedratico %><br />
    <%= f.text_area :Catedratico %>
  </div>
  <div class="field">
    <%= f.label :Nota %><br />
    <%= f.text_field :Nota %>
  </div>
  <div class="field">
    <%= f.label :Observaciones %><br />
    <%= f.text_area :Observaciones %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calificaciones/edit.html.erb
<h1>Editing calificacione</h1>

<%= render 'form' %>

<%= link_to 'Show', @calificacione %> |
<%= link_to 'Back', calificaciones_path %>

app/views/calificaciones/index.html.erb
<h1>Listing calificaciones</h1>

<table>
  <tr>
    <th>Asignatura</th>
    <th>Catedratico</th>
    <th>Nota</th>
    <th>Observaciones</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @calificaciones.each do |calificacione| %>
  <tr>
    <td><%= calificacione.Asignatura %></td>
    <td><%= calificacione.Catedratico %></td>
    <td><%= calificacione.Nota %></td>
    <td><%= calificacione.Observaciones %></td>
    <td><%= link_to 'Show', calificacione %></td>
    <td><%= link_to 'Edit', edit_calificacione_path(calificacione) %></td>
    <td><%= link_to 'Destroy', calificacione, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Calificacione', new_calificacione_path %>

app/views/calificaciones/new.html.erb
<h1>New calificacione</h1>

<%= render 'form' %>

<%= link_to 'Back', calificaciones_path %>

app/views/calificaciones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Asignatura:</b>
  <%= @calificacione.Asignatura %>
</p>

<p>
  <b>Catedratico:</b>
  <%= @calificacione.Catedratico %>
</p>

<p>
  <b>Nota:</b>
  <%= @calificacione.Nota %>
</p>

<p>
  <b>Observaciones:</b>
  <%= @calificacione.Observaciones %>
</p>


<%= link_to 'Edit', edit_calificacione_path(@calificacione) %> |
<%= link_to 'Back', calificaciones_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Examen</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>